.PHONY: clean All

All:
	@echo "----------Building project:[ Crypto - Debug ]----------"
	@cd "Crypto" && "$(MAKE)" -f  "Crypto.mk"
clean:
	@echo "----------Cleaning project:[ Crypto - Debug ]----------"
	@cd "Crypto" && "$(MAKE)" -f  "Crypto.mk" clean
